name: Protect main branch
branches:
  - pattern: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "Run Unit Tests / CI – Run Unit Tests"
          - "Lint Code / CI – Lint Code"
          - "Trivy Vulnerability Scan / Scan with Trivy"
          - "Generate SBOM / Generate CycloneDX SBOM"
          - "CodeQL Security Scan / CodeQL Security Analysis"
          - "Build Pipeline/Build GitHub Pages Site"
        # - "Deploy to Staging" # use it only is stageging job run on separate branch but on same branch this will fail because stagging will run on same branch and this condition will be required even staggin still need to run for first time.

      required_pull_request_reviews:
        required_approving_review_count: 1  #1
      enforce_admins: false  # Admins can bypass all rules
     # restrictions: null # # No restrictions, anyone with repo access can push
      restrictions: # add a whitelist
        users:
          - WahbaMousa-DevOps # <-- This line specifies who can push
        # - AnotherUserName
        # - ThirdUserName
        teams:
          - [] #  (empty, no teams)
        apps: [] # (empty, no apps)
      allow_force_pushes: true # Allows force push for those who can push and here wahba only who can force push and Admin bypass 
      allow_deletions: false
