name: Protect main branch
branches:
  - pattern: release
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI Pipeline / call-tests"
          - "CI Pipeline / call-lint" 
          - "CI Pipeline / call-trivy"
          - "CI Pipeline / call-sbom"
          - "CI Pipeline / call-codeql"
        
      required_pull_request_reviews:
        required_approving_review_count: 1 
        dismiss_stale_reviews: true 
        require_code_owner_reviews: true 
        bypass_pull_request_allowances: 
          users:
            - WahbaMousa-DevOps
      enforce_admins: false  
      restrictions:
        users:
          - WahbaMousa-DevOps  
          - github-actions[bot]
        teams: []
        apps: []
      allow_force_pushes: true 
      allow_deletions: false   
#       require_linear_history: true
#       required_conversation_resolution: true  

#       lock_branch: false # Set to true for extra protection
#       block_recreations: true
