name: Protect main branch
branches:
  - pattern: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI – Run Unit Tests"
          - "CI – Lint Code"
          - "CI - Build Project"
          - "Scan with Trivy"
          - "Generate CycloneDX SBOM"
      required_pull_request_reviews:
        required_approving_review_count: 0  #1
      enforce_admins: false  # Admins can bypass all rules
     # restrictions: null # # No restrictions, anyone with repo access can push
      restrictions: # add a whitelist
        users:
          - WahbaMousa-DevOps # <-- This line specifies who can push
        # - AnotherUserName
        # - ThirdUserName
        teams:
          - [] #  (empty, no teams)
        apps: [] # (empty, no apps)
      allow_force_pushes: true # Allows force push for those who can push and here wahba only who can force push and Admin bypass 
      allow_deletions: false
