name: Protect main branch
branches:
  - pattern: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - "CI Pipeline / call-tests"
          - "CI Pipeline / call-lint" 
          - "CI Pipeline / call-trivy"
          - "CI Pipeline / call-sbom"
          - "CI Pipeline / call-codeql"
          - "CI Pipeline / call-build"
        # - "Deploy to Staging" # use it only is stageging job run on separate branch but on same branch this will fail because stagging will run on same branch and this condition will be required even staggin still need to run for first time.

      required_pull_request_reviews:
        required_approving_review_count: 1  # Requires 1 approval for ALL users (except admins)
      enforce_admins: false  # Admins bypass ALL rules (approval + status checks)
      restrictions:
        users:
          - WahbaMousa-DevOps  # Can push directly to main branch (bypass PR process entirely)
        teams: []
        apps: []
      allow_force_pushes: true  # Only WahbaMousa-DevOps can force push to main
      allow_deletions: false   # Nobody can delete main branch