name: Protect main branch
branches:
  - pattern: main
    protection:
      required_status_checks:
        strict: true
        contexts:
          - " CI - Run Unit Tests"
          - " CI - Lint Code"
          - " CI - Build Project"
          - " Security - Trivy Scan"
          - " Generate SBOM"
      required_pull_request_reviews:
        required_approving_review_count: 1
      enforce_admins: true
      restrictions: null
      allow_force_pushes: false
      allow_deletions: false
