version: 2 #  Updates your project dependencies (libraries your code uses)
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"

  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    rebase-strategy: "auto"
