name: "🐞 Bug Report"
description: Submit a structured bug report for this project.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        ### 🧠 Before You Submit

        Please make sure you've done the following:

        - ✅ Verified you're using the latest version of this site and theme.
        - 📘 Checked the site documentation: https://aiopsvision.com/docs
        - 🔍 Searched existing issues: https://github.com/aiopsvision/aiopsvision.github.io/issues
        - 📦 This site uses the [Minimal Mistakes theme](https://mmistakes.github.io/minimal-mistakes/docs/) —  
          if the bug appears theme-related (layout, style, rendering), check their docs/issues too:  
          https://github.com/mmistakes/minimal-mistakes/issues

  - type: input
    id: bug-title
    attributes:
      label: Bug Summary
      placeholder: "E.g. Navbar not visible on mobile"
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Describe in detail how to reproduce the issue.
      placeholder: |
        1. Go to...
        2. Click on...
        3. Scroll to...
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected vs Actual Behavior
      placeholder: "Explain what you expected to happen and what happened instead"
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment Details
      value: |
        - OS: [e.g. Ubuntu 22.04]
        - Browser: [e.g. Chrome 114]
        - Jekyll version:
        - Minimal Mistakes theme version:
        - Hosting platform: [GitHub Pages / Netlify / Local]
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or Screenshots
      description: Include screenshots or terminal output if helpful.
    validations:
      required: false
