name: 📚 Documentation Fix
description: Report typos, unclear content, or outdated documentation.
labels: [documentation]
body:
  - type: markdown
    attributes:
      value: |
        ## 📘 Documentation Improvement

        Thanks for helping improve the documentation!  
        Please provide details below so we can address the issue effectively.

  - type: textarea
    id: motivation
    attributes:
      label: ✏️ What Needs Improvement?
      description: |
        What part of the documentation is confusing, outdated, or wrong?
        Please be specific (e.g., broken link, unclear section, etc.).
    validations:
      required: true

  - type: textarea
    id: suggestion
    attributes:
      label: 💡 Suggested Fix
      description: |
        How should we fix or improve it? If you have wording suggestions, include them here.
    validations:
      required: true

  - type: input
    id: affected-page
    attributes:
      label: 🔗 Link to Affected Page (if any)
      placeholder: https://aiopsvision.com/docs/...
    validations:
      required: false
