name: Auto Merge Bot

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: contains(join(github.event.pull_request.labels.*.name, ','), 'automerge') &&
        github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
      statuses: write
    steps:
      - uses: pascalgn/automerge-action@v0.16.4
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
