name: Auto Merge Bot

on:
  pull_request:
    types: [labeled]

jobs:
  automerge:
    if: contains(github.event.pull_request.labels.*.name, 'automerge') && github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
      - uses: pascalgn/automerge-action@v0.15.6
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
