name: Deploy to Production

on:
  push:
    branches:
      - main
  workflow_dispatch: {}

permissions:
  pages: write
  id-token: write

concurrency:
  group: "production-deploy"
  cancel-in-progress: false

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://wahba.aiopsvision.com
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Add CNAME
        run: echo "wahba.aiopsvision.com" > ./CNAME

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site

      - name: Upload to Pages
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./_site

      - name: Deploy to Pages
        uses: actions/deploy-pages@v4
        id: deployment

      - name: Show deployment URL
        run: echo "Deployed to production at ${{ steps.deployment.outputs.page_url }}"
        
      - name: Post-deployment verification
        run: |
          echo "Production deployment completed successfully"
          echo "Environment: production"
          echo "Branch: ${{ github.ref_name }}"
          echo "Commit: ${{ github.sha }}"
          
      - name: Smoke test production
        run: |
          echo "Running basic health checks..."
          # Add your smoke tests here if needed
          # curl -sSfL ${{ steps.deployment.outputs.page_url }} > /dev/null
          echo "Production health check completed"