name: Enforce Dynamic Branch Protection Rules 
on: 
  pull_request:
    branches: 
      - main
      # - release
  push:
    paths:
      - .github/branch-protection.yml
      - .github/scripts/parse-and-apply.py

permissions:
  contents: write  
  actions: read

jobs:
  enforce:
    if: github.repository == 'WahbaMousa-DevOps/WahbaMousa-DevOps.github.io' # Until upgrade my Org i will remove this to wrok on org also
    name: Enforce Branch Protection
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Set GH_TOKEN dynamically
        run: |
          if [[ "${{ github.repository }}" == "AIOps-Vision/WahbaMousa-DevOps.github.io" ]]; then
            echo "Using GH_TOKEN_ORG"
            echo "GH_TOKEN=${{ secrets.GH_TOKEN_ORG }}" >> $GITHUB_ENV
          else
            echo "Using GH_TOKEN_FORK"
            echo "GH_TOKEN=${{ secrets.GH_TOKEN_FORK }}" >> $GITHUB_ENV
          fi

      - name: Install GitHub CLI and PyYAML
        run: |
          sudo apt-get update
          sudo apt-get install -y gh python3-pip
          pip install pyyaml

      - name: Apply Branch Protection from YAML
        env:
          GH_TOKEN: ${{ env.GH_TOKEN }}
        run: python .github/scripts/parse-and-apply.py

